CREATE TABLE `probe`.`wordList_03` (
  `id` INT UNSIGNED NOT NULL,
  `word` CHAR(3) BINARY ASCII NOT NULL,
  PRIMARY KEY (`word`)
)
ENGINE = InnoDB
ROW_FORMAT = FIXED;

CREATE TABLE `probe`.`wordList_04` (
  `id` INT UNSIGNED NOT NULL,
  `word` CHAR(4) BINARY ASCII NOT NULL,
  PRIMARY KEY (`word`)
)
ENGINE = InnoDB
ROW_FORMAT = FIXED;

CREATE TABLE `probe`.`wordList_05` (
  `id` INT UNSIGNED NOT NULL,
  `word` CHAR(5) BINARY ASCII NOT NULL,
  PRIMARY KEY (`word`)
)
ENGINE = InnoDB
ROW_FORMAT = FIXED;

CREATE TABLE `probe`.`wordList_06` (
  `id` INT UNSIGNED NOT NULL,
  `word` CHAR(6) BINARY ASCII NOT NULL,
  PRIMARY KEY (`word`)
)
ENGINE = InnoDB
ROW_FORMAT = FIXED;

CREATE TABLE `probe`.`wordList_07` (
  `id` INT UNSIGNED NOT NULL,
  `word` CHAR(7) BINARY ASCII NOT NULL,
  PRIMARY KEY (`word`)
)
ENGINE = InnoDB
ROW_FORMAT = FIXED;

CREATE TABLE `probe`.`wordList_08` (
  `id` INT UNSIGNED NOT NULL,
  `word` CHAR(8) BINARY ASCII NOT NULL,
  PRIMARY KEY (`word`)
)
ENGINE = InnoDB
ROW_FORMAT = FIXED;

CREATE TABLE `probe`.`wordList_09` (
  `id` INT UNSIGNED NOT NULL,
  `word` CHAR(9) BINARY ASCII NOT NULL,
  PRIMARY KEY (`word`)
)
ENGINE = InnoDB
ROW_FORMAT = FIXED;

CREATE TABLE `probe`.`wordList_10` (
  `id` INT UNSIGNED NOT NULL,
  `word` CHAR(10) BINARY ASCII NOT NULL,
  PRIMARY KEY (`word`)
)
ENGINE = InnoDB
ROW_FORMAT = FIXED;



CREATE TABLE `probe`.`wordList_11` (
  `id` INT UNSIGNED NOT NULL,
  `word` CHAR(11) BINARY ASCII NOT NULL,
  PRIMARY KEY (`word`)
)
ENGINE = InnoDB
ROW_FORMAT = FIXED;

CREATE TABLE `probe`.`wordList_12` (
  `id` INT UNSIGNED NOT NULL,
  `word` CHAR(12) BINARY ASCII NOT NULL,
  PRIMARY KEY (`word`)
)
ENGINE = InnoDB
ROW_FORMAT = FIXED;

CREATE TABLE `probe`.`wordList_13` (
  `id` INT UNSIGNED NOT NULL,
  `word` CHAR(13) BINARY ASCII NOT NULL,
  PRIMARY KEY (`word`)
)
ENGINE = InnoDB
ROW_FORMAT = FIXED;


CREATE TABLE `probe`.`wordList_14` (
  `id` INT UNSIGNED NOT NULL,
  `word` CHAR(14) BINARY ASCII NOT NULL,
  PRIMARY KEY (`word`)
)
ENGINE = InnoDB
ROW_FORMAT = FIXED;


CREATE TABLE `probe`.`wordList_15` (
  `id` INT UNSIGNED NOT NULL,
  `word` CHAR(15) BINARY ASCII NOT NULL,
  PRIMARY KEY (`word`)
)
ENGINE = InnoDB
ROW_FORMAT = FIXED;


